# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

services:
  peer0.hospitaladmin.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  peer0.clinicalstaff.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  peer0.diagnosticstaff.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  peer0.pharmacy.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  peer0.insurance.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg

  peer0.patientaccess.example.com:
    volumes:
      - ./podman/peercfg:/etc/hyperledger/peercfg
